# Site settings
title: Ruizhi Ma's Blog
SEOTitle: Ruizhi Ma's Blog
header-img: img/post-bg-desk.jpg
email: sobermrz@gmail.com
description: "脚踏实地 仰望星空"
keyword: "Ruizhi Ma's Blog"
url: "http://sobermrz.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/sobermrz/sobermrz.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "路漫漫其修远兮 吾将上下而求索"
sidebar-avatar: /img/myself-img.JPG      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
github_username:    sobermrz




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: ruizhima

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 32934f12627c20cb5cea                            #生成的clientID
  clientSecret: 2922384f5a740f97c8ee4ec8256caf44200fc39a    #生成的clientSecret
  repo: sobermrz.github.io    #仓库名称
  owner: sobermrz    #github用户名
  admin: sobermrz
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# # Friends
# friends: [
#     {
#         title: "WY",
#         href: "http://zhengwuyang.com"
#     },{
#         title: "简书·BY",
#         href: "http://www.jianshu.com/u/e71990ada2fd"
#     },{
#         title: "Apple",
#         href: "https://apple.com"
#     },{
#         title: "Apple Developer",
#         href: "https://developer.apple.com/"
#     }
# ]